[package]
name = "spacial_sound"
version = "0.0.1"
author = "Mitchell Tsutsulis mitchell444999@protonmail.com"

[[bin]]
name = "spacial_sound"
path = "src/main.rs"

[dependencies]
relative-path = "1.5.0"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["ttf", "mixer"]
